### ISSUE TITLE
Configure OCP cost as $X/month/node

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1238]
## Update January 20, 2020

This has come back to dev after initial QA. There's two bits we need to add in to pass QA. 

-  When we create the summary line item for the node cost here: https://github.com/project-koku/koku/pull/1438/files#diff-5132f3be415e3032124d987a0aff4939R770 we are missing some important information. 
   -  We need to alter that method to create a new row for each node. 
   - We need each new row to have `cluster_id`, `cluster_alias`, and `report_period_id` as included data
   - Adding these fields will cause this row to be deleted when we delete a provider
- Once we have a row per node in this table, then we need to update the APIs to return sum('monthly_cost') for the cluster when we group by cluster. Having the cluster_id and cluster_alias added to the row will allow us to do this. 

## User Story
As a Koku customer, I want to see my billing cost for OCP usage as my configured $X/month/node.

## Assumptions
- This needs UX discussion around how we gather inputs.
  - We accept that this initial implementation is API-only and may be revised as UI/UX discussions unfold.
- See: https://cloud.redhat.com/beta/cost-management/cost-models
- Input definition is to perhaps add "node" alongside CPU/Memory/etc in the "add rate" UI, etc. We accept that we are going to make some assumptions about this interaction and may need to revisit the implementation once UX provides feedback.
- If defined, this applies to _all_ OCP nodes for the customer's provider/source.
- In terms of unit testing, we do not intend to exhaustively verify the SQL beyond the pattern used to currently test/verify the affected reports. We will likely spot-check some particular use cases manually or have very specific unit tests for specific known use cases.

## Questions and Answers
- Q: how is this output value presented in the UI?
- A: This affects derived cost. Cost model has 2 components: price list and markup. Anything from price list we call a derived cost. Anything from markup we call markup cost. We also return infrastructure cost which is just the cost directly from the provider.
- Q: do we calculate fractional rates, round, or ceiling? (e.g. does 1 node running only for 10 days of a 30-day month mean it accrues 1/3 the rate?) If fractional, does this really mean that we internally multiply and treat the rates as "per second"?
- A: Regardless of how much you use it, you get the whole month charge. So, this effectively acts like a ceiling. This is intended to mimic the customer contract with openshift. This means that if you look at the cost for a node on Day 1 vs Day 30 of the month, you see this contribute to the full cost either way. We are not going to consider amortizing the cost across the month's days.
- Remember that this does not replace other cost calculations; it adds to them. (such as hourly CPU, etc)
- Q: one rate for all OCP providers under my account? or one rate PER OCP provider?
  - A: cost models are stored/modeled independent of provider, and customer associates provider with cost models.
- Q: how/where does the user associate the provider with particular cost models?
- A: Choose [a most model](https://ci.cloud.redhat.com/beta/hybrid/cost-management/cost-models), click the Sources tab, click Assign Source, and choose the relevant source(s).

## Acceptance Criteria

- [ ] APIs exist or have been updated to allow the customer to CRUD the new type of $/month/node cost model for OCP only.
  - See also this UI: https://ci.cloud.redhat.com/beta/hybrid/cost-management/cost-models
  - But we do not expect the UI to be updated immediately with this story.
- [ ] APIs have been updated to allow client to see newly calculated data.
  - See also the APIs for this list view: https://ci.cloud.redhat.com/beta/hybrid/cost-management/ocp?group_by[project]=*&order_by[cost]=desc
- [ ] Verify that within a cost model, only one of this type $/month/node can exist.
  - This is consistent with the other types. There should only ever be 0 or 1 within each cost model instance.
- [ ] Another issue exists to track any remaining UI/UX followup work and is referenced here (in comments below).

**Comment by werwty** [comment]
@adberglund What should be done in the costs_by_project case?
Correct me if I'm wrong, but if projects can share the same nodes, and we count the cost of those nodes for a project, the sum(project_node) cost would be greater than it actually is.

**Comment by werwty** [comment]
@chargio What do you want to see in the costs_by_project view? 
Say project 1 uses [node1, node2] and project2 uses [node2, node3], should the monthly cost for project1 and project2 be 2*node_cost? Or is there some other way to divvy up the cost?

**Comment by chargio** [comment]
Let's have a conversation with us, as I believe we are doing things differently than I thought we were.

**Comment by werwty** [comment]
Demo of current functionality: https://asciinema.org/a/y8rCV80zmY5DETv1mS6MOT1eT

**Comment by lcouzens** [comment]
Pushing this back to review as I am seeing two things potentially wrong with this. 

Firstly each daily line item shows monthly_cost for the node month value, I feel like we should only show this at the totals level over each daily line item.

Secondly when you add a month/node value to a cost model and ingest data the month node value always shows up in the 1st of the month line item exclusively. See below

```
{
    "meta": {
        "count": 10,
        "filter": {
            "time_scope_value": "-10",
            "time_scope_units": "day",
            "resolution": "daily"
        },
        "group_by": {},
        "order_by": {},
        "total": {
            "cost": {
                "value": 298.955,
                "units": "USD"
            },
            "infrastructure_cost": null,
            "derived_cost": {
                "value": 288.955,
                "units": "USD"
            },
            "markup_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "monthly_cost": {
                "value": 10.0,
                "units": "USD"
            }
        }
    },
    "links": {
        "first": "/api/cost-management/v1/reports/openshift/costs/?limit=100&offset=0",
        "next": null,
        "previous": null,
        "last": "/api/cost-management/v1/reports/openshift/costs/?limit=100&offset=0"
    },
    "data": [
        {
            "date": "2019-11-30",
            "values": [
                {
                    "date": "2019-11-30",
                    "cost": {
                        "value": 30.3,
                        "units": "USD"
                    },
                    "infrastructure_cost": null,
                    "derived_cost": {
                        "value": 30.3,
                        "units": "USD"
                    },
                    "markup_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "monthly_cost": {
                        "value": 0.0,
                        "units": "USD"
                    }
                }
            ]
        },
        {
            "date": "2019-12-01",
            "values": [
                {
                    "date": "2019-12-01",
                    "cost": {
                        "value": 40.43,
                        "units": "USD"
                    },
                    "infrastructure_cost": null,
                    "derived_cost": {
                        "value": 30.43,
                        "units": "USD"
                    },
                    "markup_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "monthly_cost": {
                        "value": 10.0,
                        "units": "USD"
                    }
                }
            ]
        },
        {
            "date": "2019-12-02",
            "values": [
                {
                    "date": "2019-12-02",
                    "cost": {
                        "value": 30.43,
                        "units": "USD"
                    },
                    "infrastructure_cost": null,
                    "derived_cost": {
                        "value": 30.43,
                        "units": "USD"
                    },
                    "markup_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "monthly_cost": {
                        "value": 0.0,
                        "units": "USD"
                    }
                }
            ]
        },
```
One other thing to mention is when you remove the provider/cost model with that month node value we dont remove that 1st of the month line item with the monthly node cost.

```
{
    "meta": {
        "count": 10,
        "filter": {
            "time_scope_value": "-10",
            "time_scope_units": "day",
            "resolution": "daily"
        },
        "group_by": {},
        "order_by": {},
        "total": {
            "cost": {
                "value": 10.0,
                "units": "USD"
            },
            "infrastructure_cost": null,
            "derived_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "markup_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "monthly_cost": {
                "value": 10.0,
                "units": "USD"
            }
        }
    },
    "links": {
        "first": "/api/cost-management/v1/reports/openshift/costs/?limit=100&offset=0",
        "next": null,
        "previous": null,
        "last": "/api/cost-management/v1/reports/openshift/costs/?limit=100&offset=0"
    },
    "data": [
        {
            "date": "2019-11-30",
            "values": []
        },
        {
            "date": "2019-12-01",
            "values": [
                {
                    "date": "2019-12-01",
                    "cost": {
                        "value": 10.0,
                        "units": "USD"
                    },
                    "infrastructure_cost": null,
                    "derived_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "markup_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "monthly_cost": {
                        "value": 10.0,
                        "units": "USD"
                    }
                }
            ]
        },
```

**Comment by werwty** [comment]
>Firstly each daily line item shows monthly_cost for the node month value, I feel like we should only show this at the totals level over each daily line item.

I don't have a preference about this. But if the user gets the usage for 2 month, the monthly_cost on the totals level would show the sum. If we show it on the daily line item level it's clearer how much each month contributed to the total.  @adberglund What are your thoughts about this?

>Secondly when you add a month/node value to a cost model and ingest data the month node value always shows up in the 1st of the month line item exclusively. 

This is by design because we do not amortize the cost across the month's days. If the node gets used in the month, the node/month charge gets added to the month's charge. Adding it to the first of the month ensures that this happens.

>One other thing to mention is when you remove the provider/cost model with that month node value we dont remove that 1st of the month line item with the monthly node cost.

Good catch! I will fix this.

**Comment by lcouzens** [comment]
I think its worth discussing. I agree if the request 2 months of data then the total value would contain tallied cost but I think thats possibly ok as thats what was request. At the same time `monthly_cost` is not really clear what that is exactly, especially if it has multiple months tallied together so it could still be confusing. Maybe it needs to be `total_monthly_costs` or something.

As for showing the monthly cost on the 1st of the month, I get that and it probably does make sense unless we had a specific line item for general month/node costs. At the same time its a little confusing having monthly_cost on each daily line item but everything shows as a zero except for the 1st of the month. To me it implies you *could* have different values in each of those daily line items so this could also confusing. Perhaps we could only show `monthly_cost` on the 1st and not show it at all on the remaining days in that month.

**Comment by chargio** [comment]
I agree that there are two ways of showing this information:
- As a monthly cost,show it at the beginning of the month, in the same way that AWS does. This shows when things are happening and the fact that there are happening together. (CAPEX view). It does not reflect the fact that the value is being accrued per day (or per hour)
- As a daily version of above. It is not accurate but reflects better the daily costs. (OPEX view or just a view of the depreciation of the asset). 

The same thing is going to happen with licensing if we want to show a true view of the costs. You pay a license once a year (for instance), but you actually use a part of it every day/month.

I would be in favor of making it clear that the subscription is monthly and then being able to show in the interface the information as happening in the first or last day of the month, or just spread through the month in daily chunks. However, it is important that we can differentiate as the concepts are different.

![Cost Model - CAPEX vs OPEX](https://user-images.githubusercontent.com/7500590/70506800-6e856100-1b2b-11ea-926c-284067eaf421.png)

**Comment by chargio** [comment]
A monthly version of this picture
![Cost Model - Monthly vs daily](https://user-images.githubusercontent.com/7500590/70521620-ccbc3f00-1b3f-11ea-982c-ab49631ba65a.png)

**Comment by lcouzens** [comment]
@werwty Did you fix the clean up on provider/cost model delete?? I still see that bug.


```One other thing to mention is when you remove the provider/cost model with that month node value we dont remove that 1st of the month line item with the monthly node cost.```

`Good catch! I will fix this. `

**Comment by werwty** [comment]
@lcouzens I swear I fixed that issue.
Can you take a look at this demo and see what I'm missing? As far as I can tell the derived cost is recalculated when the cost model is removed.
https://asciinema.org/a/9tUUONMOwpojMoYdWUjoID17L

**Comment by lcouzens** [comment]
@werwty Looking at your demo it looks correct but pulling latest and running for me I am still seeing the node month cost left over after removing provider + cost model. Any chance you could give it a go?

**Comment by werwty** [comment]
Just a note though, the recalculation is an async task that gets kicked off, so it might be some seconds before the derived cost is updated. 
I'll check out the latest later today and give it a go just to be sure.

**Comment by lcouzens** [comment]
Yeh I wondered that, I left it a good while and even tried a resummary but still didnt work. Appreciate you having a look.

**Comment by werwty** [comment]
OK I see where the problem is- when the provider is deleted first, deleting the cost model will not recalculate the derived cost.

I'm not quite sure what the correct behavior is in this case. As far as I can tell when providers are deleted the line items generated from them are not removed. Is that what the resummary does? What's the api end point for that?

**Comment by lcouzens** [comment]
Interesting I thought the line items were deleted. So your saying if I remove the cost_model prior to deleting the provider it should work?

The resummary recalculates the table data for the api I believe, my thought it that the data was removed from the tables but not surfaced to the api so I tried a resummary but that didnt work. @adberglund correct me if im wrong about my assumption. 

As for the endpoint its http://localhost:5000/api/v1/report_data/?provider_uuid=*&start_date=2020-01-01

**Comment by lcouzens** [comment]
Another thing I just noticed is when doing a group_by[cluster]=x we don't see the month/node cost in the report. My thoughts are that you can have many nodes to a cluster so we should see that costing.

As a side note we do however see month/node costs when doing a group_by[node]=x

**Comment by werwty** [comment]
> Interesting I thought the line items were deleted. 

I just had another look and I'm be wrong about this. I was looking for a provider relation with cascade delete in the LineItemSummary model, but I missed that the report_period gets deleted when the provider get deleted and that in turn cascade deletes the line item summary. My bad.

> So your saying if I remove the cost_model prior to deleting the provider it should work?

That is correct.

> Another thing I just noticed is when doing a group_by[cluster]=x we don't see the month/node cost in the report. My thoughts are that you can have many nodes to a cluster so we should see that costing.

Seems reasonable. 

@adberglund I recommend filing a separate bugs/enhancements for the group_by cluster, since that seems nontrivial and probably needs more discussion. 
And either filing the provider deletion not removing the derived cost as a separate bug or put this item back in the backlog. I will be happy to answer questions about how the $/node/month cost is calculated and stored if whoever is fixing this has any questions.

**Comment by lcouzens** [comment]
Verified
Commit: 7f641fa8ec42be6045713530e83f21f40bf79697
Automation: test_api_ocp_provider_crud_upload_service
